### ISSUE TITLE
how to use with mobile / rest like web api 2?

### ISSUE THREAD

**Issue by RickTheHat** [brockallen/BrockAllen.IdentityReboot#9]
i'm bashing my head b/c i'm now trying to upgrade my website from the OLD simple membership to use identity + i'm also creating a new mobile app so trying to find a solution to fit all the goodies you provide (membership + identity reboot) along with having a REST way to login for my mobile app using the same project/same db is painful.

what are other people doing to handle this? is there any good options without having to have multiple projects?

**Comment by brockallen** [comment]
Sorry -- this issue fell off my radar. 

So you're describing something that has many moving parts. For the mobile app to obtain a token, look into OAuth2. For the part of OAuth2 where the user would enter credentials look into MembershipReboot as your identity management library. If you don't want to use MR, then you could use Asp.Net Identity instead (tho I don't think it's as good as MR). To help improve Asp.Net Identity so that it's closer to the strong protections that MR provides, then you can integrate IdentityReboot.

HTH
